spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/gtp_test
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8081